# Generated by Django 4.2.9 on 2024-01-31 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customusermodel",
            name="last_name",
        ),
    ]
