# Generated by Django 4.2.9 on 2024-01-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Job_title", models.CharField(max_length=255)),
                ("Id_number", models.CharField(max_length=20)),
                ("Phone", models.CharField(max_length=20)),
                ("Email", models.EmailField(max_length=254)),
            ],
        ),
    ]
